version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
    groups:
      rollup:
        update-types:
          - major
          - minor
          - patch
