app = "go-ji"
primary_region = "sea"

[build]
  image = "ghcr.io/kejadlen/go-ji:fly"

[env]
  GO_JI_SENTRY_ENVIRONMENT = "production"
  TAILSCALE_HOSTNAME = "go"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[http_service.checks]]
  grace_period = "5s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/up"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256

[mounts]
  source = "go_ji"
  destination = "/data"
