[project]
requires-python = ">=3.12"
name = "go-ji"
version = "0.1.0"
dependencies = [
    "alembic",
    "Flask",
    "SQLAlchemy",
]

[project.optional-dependencies]
dev = [
    "coverage",
    "pip-tools",
    "pyright",
    "pytest",
    "ruff",
    "ruff-lsp",
]

[tool.pip-tools]
generate-hashes = true
# silence warning that strip-extras will be the default in 8.0.0, at which
# point this setting can be removed
strip-extras = true

[tool.ruff]
target-version = "py312"

[tool.ruff.lint]
select = ["F", "E4", "E7", "E9", "W", "I", "N"]

[tool.ruff.format]
docstring-code-format = true
