target-version = "py312"

[lint]
select = [
    "F",   # pyflakes
    "E4", "E7", "E9", "W", # pycodestyle
    "I",   # isort
    "N",   # pep8-naming
    "UP",  # pyupgrade
    "ANN", # flake8-annotations
    "TCH", # flake8-type-checking
    "RUF", # ruff
]
ignore = [
    "E741", # allow ambiguous variable names
]

[lint.per-file-ignores]
"tests/**/*.py" = ["ANN"]

[format]
docstring-code-format = true
