# https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_run
# https://fly.io/docs/app-guides/continuous-deployment-with-github-actions/

name: Deploy
on:
  workflow_run:
    workflows: [Build]
    types: [completed]
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    concurrency: deploy-group
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          docker pull ${IMAGE}:$(git rev-parse --short HEAD)
          docker tag ${IMAGE}:$(git rev-parse --short HEAD) ${IMAGE}:fly
          docker push ${IMAGE}:fly
        env:
          IMAGE: ghcr.io/${{ github.repository }}

      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
